# Generated by Django 2.0.1 on 2018-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('text', models.TextField()),
                ('text_md5', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('response_time', models.IntegerField()),
                ('messages', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('action_method', models.CharField(max_length=10)),
                ('api', models.CharField(max_length=200)),
                ('headers', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('cookies', models.CharField(max_length=200)),
                ('headers_desc', models.CharField(max_length=200)),
                ('body_desc', models.CharField(max_length=200)),
                ('cookies_desc', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
